version: '3.1'

services:

  db:
    container_name: database
    image: mysql:5.5
    hostname: database
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_USER: shephertz
      MYSQL_PASSWORD: AppP@ssw0rd
      MYSQL_DATABASE: app42paas
      MYSQL_ROOT_PASSWORD: RootP@ssw0rd

  tomcat:
    container_name: tomcat
    hostname: tomcat
    build:
      context: ./build
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: shephertz
      DB_PASSWORD: AppP@ssw0rd
      DB_IP: database
      DB_NAME: app42paas

volumes:
  mysql_data:
