version: '3.1'

services:

  mysql:
    container_name: mysql
    image: mysql:5.5
    hostname: mysql
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_USER: shephertz
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: app42paas
      MYSQL_ROOT_PASSWORD: rootsecret

  tomcat:
    container_name: tomcat
    hostname: tomcat
    build:
      context: ./build
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: shephertz
      DB_PASSWORD: secret
      DB_IP: mysql
      DB_NAME: app42paas

volumes:
  mysql_data:
